### ISSUE TITLE
Remove duplicate id from date

### ISSUE THREAD

**Issue by Znbiz** [mts-ai/FastAPI-JSONAPI#19]
In responses, all attributes of the as is object should be returned, including “id”, which leads to duplication: “id” appears both in attributes and one level higher, in “data”.
However, according to JSON:API, attributes cannot have fields named “type” or “id” - they are reserved: https://jsonapi.org/format/1.1/#document-resource-object-fields

**Comment by mahenzon** [comment]
fixed in 1.0.0
