### ISSUE TITLE
Filters: datetime filter example not working

### ISSUE THREAD

**Issue by Huuhailija** [mts-ai/FastAPI-JSONAPI#50]
When you define SQLalchemy model with:

![kuva](https://github.com/mts-ai/FastAPI-JSONAPI/assets/19683379/7c1c66ed-4b97-4e06-97b8-c6c3d936e270)

and make schema according to:

![kuva](https://github.com/mts-ai/FastAPI-JSONAPI/assets/19683379/e399cda7-57ef-45a9-b76f-7800d4428268)

Then you produce error at filter creation in sqlalchemy.py at line 86 trying to cast type(value) to datetime, when filter value is str format.

![kuva](https://github.com/mts-ai/FastAPI-JSONAPI/assets/19683379/84dea088-83ac-4744-a7d5-10316bd904c2)

Seems like it's not intended to use datetime value in filtering. Changing schema to str will fix the error, but will result more problems later with ORM models which expects datetime matching column. 

Using filter example in SwaggerUI as filter parameter.

![kuva](https://github.com/mts-ai/FastAPI-JSONAPI/assets/19683379/8f2c513a-6956-4b16-9913-b789b6e097a3)

**Comment by Huuhailija** [comment]
The issue seems to present in the repo example too. https://github.com/mts-ai/FastAPI-JSONAPI/tree/main/examples/api_for_sqlalchemy

**Comment by Huuhailija** [comment]
Making clear_value = datetime.strptime(value, '%Y-%m-%dT%H:%M:%S.%f'), will fix the issue and the underlying query filter will work as expected returning records between timestamps. This method needs to cast datetimes properly for filtering to work. Hope this will be updated soon.

**Comment by mahenzon** [comment]
ouch, thank you, we'll take a look
