### ISSUE TITLE
Error in is_ and isnot Filters in API Requests

### ISSUE THREAD

**Issue by gnc-git** [mts-ai/FastAPI-JSONAPI#54]
**Description**
We have encountered an issue in the API when using the is_ and isnot filters for nullability checks, specifically on the email field of the User model. This leads to unexpected behavior or errors in the response. [Test cases](https://github.com/mts-ai/FastAPI-JSONAPI/pull/53) demonstrating the issue are attached.

**Steps to Reproduce**
Perform a GET request to the API endpoint /users with a filter to check if email is null (e.g., ?filter=[{"name": "email", "op": "is_", "val": null}]).
Perform a similar GET request with a filter to check if email is not null (e.g., ?filter=[{"name": "email", "op": "isnot", "val": null}]).

**Expected Behavior**
The API should correctly process these filter requests, returning users whose email fields match the specified conditions (either null or not null).

**Actual Behavior**
The API is either not returning the correct set of users (those with null or not null email fields), or it's causing an SQL syntax error, particularly when using the is_ and isnot operations.

**Comment by mahenzon** [comment]
fixed in #60
